/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b8f85ccc-df25-40a6-97e3-fdf0d5ef3d3b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_473awVu47",
    "aws_user_pools_web_client_id": "3hn9gktd9jvjau9c360ekft6dg",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jhadpxrzuvgfrnz5sqhhpvep74.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
